### ISSUE TITLE
0 prefix for octal

### ISSUE THREAD

**Issue by Alexey-T** [avk959/str2int-alter#2]
>IMO there is only one significant difference from Val(): since the lone leading zero is the prefix of an octal string, decimal strings cannot start with a zero. 

It should not be like this- it must try octal notation only after & prefix (supported by FPC).

and binary notation - only after % prefix.

**Comment by avk959** [comment]
Why?

**Comment by Alexey-T** [comment]
no documentation for FPC says that 0 is octal prefix.

**Comment by avk959** [comment]
So this is an extension. Other languages don't seem to care about FPC documentation?

**Comment by Alexey-T** [comment]
Ok, you are a boss.

**Comment by avk959** [comment]
However, the problem can be solved using conditional compilation, but this will also affect the tests. Can you take over the editing of tests?
By the way, the current documentation of Val() is rather poor and does not contain an adequate description of its behavior.

**Comment by Alexey-T** [comment]
sorry, I cannot. I just wanted to disable 0 as octal prefix, that's it.

**Comment by avk959** [comment]
Just try replacing the current MainCaseMacro with this one: 
```
  case p^ of
    '$': Result := ConvFunMacro(p+1, aCount-1, TypeMacro rxHex, OutMacro);
    '%': Result := ConvFunMacro(p+1, aCount-1, TypeMacro rxBin, OutMacro);
    '&': Result := ConvFunMacro(p+1, aCount-1, TypeMacro rxOct, OutMacro);
    '0':
      begin
        if aCount = 1 then
          begin
            aValue := 0;
            exit(True);
          end;
        case p[1] of
          '0'..'9':
            begin
              SetDecTrueMacro
              Result := ConvFunMacro(p+1, aCount-1, TypeMacro rxDec, OutMacro);
            end;
          'X', 'x': Result := ConvFunMacro(p+2, aCount-2, TypeMacro rxHex, OutMacro);
        end;
      end;
    '1'..'9':
      begin
        SetDecTrueMacro
        Result := ConvFunMacro(p, aCount, TypeMacro rxDec, OutMacro);
      end;
    'X', 'x': Result := ConvFunMacro(p+1, aCount-1, TypeMacro rxHex, OutMacro)
  end; 
```
It seems like it should work, but the tests are likely to fail.

**Comment by avk959** [comment]
See b750fea8

**Comment by Alexey-T** [comment]
Thanks, ok now.
